- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: 0777

- name: Ensure Nginx is running
  service:
    name: nginx
    state: restarted
    enabled: yes
